/** Preset permission rule suggestions keyed by field path */
export const PERMISSION_SUGGESTIONS: Record<string, string[]> = {
  "permissions.allow": [
    "Read",
    "Write",
    "Edit",
    "Bash",
    "Glob",
    "Grep",
    "WebFetch",
    "WebSearch",
    "Task",
    "Bash(npm test)",
    "Bash(pnpm test)",
    "Bash(git *)",
    "Bash(npm run *)",
    "Bash(pnpm run *)",
    "Bash(npx *)",
    "Bash(node *)",
  ],
  "permissions.deny": [
    "Bash(rm -rf *)",
    "Bash(curl * | bash)",
    "Bash(eval *)",
    "Bash(sudo *)",
    "Bash(chmod *)",
    "WebFetch",
    "Bash(npm publish)",
    "Bash(git push --force *)",
  ],
  "permissions.ask": [
    "Bash",
    "WebFetch",
    "WebSearch",
    "Edit",
    "Write",
    "Task",
    "Bash(npm publish)",
    "Bash(git push *)",
    "Bash(docker *)",
    "Bash(rm *)",
  ],
};
