import type { InstallMethod, ToolCategory, ToolDefinition } from "@/lib/types/toolbox";

export const DEFAULT_TOOLS: ToolDefinition[] = [
  {
    id: "homebrew",
    name: "Homebrew",
    category: "package-manager",
    description: "macOS/Linux package manager",
    binary: "brew",
    versionCommand: "brew --version",
    versionParser: "regex",
    versionRegex: "Homebrew ([\\d.]+)",
    installUrl: "https://brew.sh",
    installCommand: '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"',
    updateCommands: { default: "brew update" },
    detectInstallMethod: false,
    latestVersionSource: { type: "github-release", repo: "Homebrew/brew" },
    usedFor: "Core — macOS package manager for installing other tools",
  },
  {
    id: "node",
    name: "Node.js",
    category: "runtime",
    description: "JavaScript runtime",
    binary: "node",
    versionCommand: "node --version",
    versionParser: "semver-line",
    installUrl: "https://nodejs.org",
    installCommand: "brew install node",
    updateCommands: { homebrew: "brew upgrade node", default: "brew upgrade node" },
    latestVersionSource: { type: "url", url: "https://nodejs.org/dist/index.json", parser: "nodejs-lts" },
    usedFor: "Core — ClaudeKit and all web/desktop projects",
  },
  {
    id: "nvm",
    name: "nvm",
    category: "dev-tool",
    description: "Node version manager",
    binary: "nvm",
    versionCommand: 'bash -c "source ~/.nvm/nvm.sh 2>/dev/null && nvm --version"',
    versionParser: "first-line",
    installUrl: "https://github.com/nvm-sh/nvm",
    installCommand: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash",
    updateCommands: { default: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash" },
    detectInstallMethod: false,
    latestVersionSource: { type: "github-release", repo: "nvm-sh/nvm" },
    shellFunction: true,
    usedFor: "Core — manage multiple Node.js versions",
  },
  {
    id: "pnpm",
    name: "pnpm",
    category: "package-manager",
    description: "Fast, disk space efficient package manager",
    binary: "pnpm",
    versionCommand: "cd ~ && pnpm --version",
    versionParser: "first-line",
    installUrl: "https://pnpm.io/installation",
    installCommand: "npm install -g pnpm",
    updateCommands: {
      homebrew: "brew upgrade pnpm",
      npm: "npm install -g pnpm@latest",
      default: "cd ~ && pnpm self-update",
    },
    shellFunction: true,
    latestVersionSource: { type: "npm", package: "pnpm" },
    usedFor: "Core — ClaudeKit monorepo package manager",
  },
  {
    id: "npm",
    name: "npm",
    category: "package-manager",
    description: "Node package manager (bundled with Node.js)",
    binary: "npm",
    versionCommand: "npm --version",
    versionParser: "first-line",
    installUrl: "https://docs.npmjs.com/downloading-and-installing-node-js-and-npm",
    installCommand: "npm install -g npm@latest",
    updateCommands: { homebrew: "brew upgrade node", default: "npm install -g npm@latest" },
    latestVersionSource: { type: "npm", package: "npm" },
    usedFor: "Core — Node.js package manager",
  },
  {
    id: "npx",
    name: "npx",
    category: "dev-tool",
    description: "Bundled with Node.js — execute npm packages without installing",
    binary: "npx",
    versionCommand: "npx --version",
    versionParser: "first-line",
    installUrl: "https://docs.npmjs.com/cli/v10/commands/npx",
    updateCommands: { default: "npm install -g npm@latest" },
    detectInstallMethod: false,
    latestVersionSource: { type: "none" },
    usedFor: "Core — run npm packages without installing",
  },
  {
    id: "bun",
    name: "Bun",
    category: "runtime",
    description: "Fast all-in-one JavaScript runtime & toolkit",
    binary: "bun",
    versionCommand: "bun --version",
    versionParser: "first-line",
    installUrl: "https://bun.sh",
    installCommand: "curl -fsSL https://bun.sh/install | bash",
    updateCommands: { homebrew: "brew upgrade bun", default: "bun upgrade" },
    latestVersionSource: { type: "github-release", repo: "oven-sh/bun" },
    usedFor: "Alternative Node.js runtime",
  },
  {
    id: "git",
    name: "Git",
    category: "vcs",
    description: "Distributed version control system",
    binary: "git",
    versionCommand: "git --version",
    versionParser: "regex",
    versionRegex: "git version ([\\d.]+)",
    installUrl: "https://git-scm.com/downloads",
    installCommand: "brew install git",
    updateCommands: { homebrew: "brew upgrade git" },
    latestVersionSource: { type: "github-release", repo: "git/git" },
    usedFor: "Core — version control",
  },
  {
    id: "gh",
    name: "GitHub CLI",
    category: "vcs",
    description: "GitHub's official command-line tool",
    binary: "gh",
    versionCommand: "gh --version",
    versionParser: "regex",
    versionRegex: "gh version ([\\d.]+)",
    installUrl: "https://cli.github.com",
    installCommand: "brew install gh",
    updateCommands: { homebrew: "brew upgrade gh" },
    latestVersionSource: { type: "github-release", repo: "cli/cli" },
    usedFor: "Core — GitHub integration",
  },
  {
    id: "claude",
    name: "Claude Code",
    category: "ai-tool",
    description: "Anthropic's Claude Code CLI",
    binary: "claude",
    versionCommand: "claude --version",
    versionParser: "semver-line",
    installUrl: "https://docs.anthropic.com/en/docs/claude-code",
    installCommand: "npm install -g @anthropic-ai/claude-code",
    updateCommands: {
      homebrew: "brew upgrade claude-code",
      npm: "npm update -g @anthropic-ai/claude-code",
      default: "npm update -g @anthropic-ai/claude-code",
    },
    brewPackage: "claude-code",
    latestVersionSource: { type: "npm", package: "@anthropic-ai/claude-code" },
    usedFor: "Core — AI-powered scaffolding and design iteration",
  },
  {
    id: "python",
    name: "Python",
    category: "runtime",
    description: "Python programming language",
    binary: "python3",
    versionCommand: "python3 --version",
    versionParser: "regex",
    versionRegex: "Python ([\\d.]+)",
    installUrl: "https://www.python.org/downloads/",
    installCommand: "brew install python",
    updateCommands: { homebrew: "brew upgrade python" },
    latestVersionSource: { type: "url", url: "https://endoflife.date/api/python.json", parser: "python-eol" },
    usedFor: "Inside — Game projects (Pygame), CLI tools",
  },
  {
    id: "docker",
    name: "Docker",
    category: "dev-tool",
    description: "Container platform for building and running apps",
    binary: "docker",
    versionCommand: "docker --version",
    versionParser: "regex",
    versionRegex: "Docker version ([\\d.]+)",
    installUrl: "https://docs.docker.com/get-docker/",
    installCommand: "brew install --cask docker",
    updateCommands: { homebrew: "brew upgrade --cask docker" },
    latestVersionSource: { type: "github-release", repo: "moby/moby" },
    usedFor: "Optional — container-based workflows",
  },
  {
    id: "playwright",
    name: "Playwright",
    category: "dev-tool",
    description: "Browser automation for screenshots and testing",
    binary: "npx",
    versionCommand: "npx playwright --version",
    versionParser: "regex",
    versionRegex: "Version ([\\d.]+)",
    installUrl: "https://playwright.dev",
    installCommand: "npx playwright install chromium",
    updateCommands: { default: "npx playwright install chromium" },
    detectInstallMethod: false,
    latestVersionSource: { type: "npm", package: "playwright" },
    usedFor: "B4U — screenshots and browser automation",
  },
  {
    id: "ffmpeg",
    name: "FFmpeg",
    category: "dev-tool",
    description: "Media processing toolkit for audio/video merging",
    binary: "ffmpeg",
    versionCommand: "ffmpeg -version",
    versionParser: "regex",
    versionRegex: "ffmpeg version ([\\d.]+)",
    installUrl: "https://ffmpeg.org",
    installCommand: "brew install ffmpeg",
    updateCommands: { homebrew: "brew upgrade ffmpeg" },
    latestVersionSource: { type: "github-release", repo: "FFmpeg/FFmpeg" },
    usedFor: "B4U — audio/video processing for walkthroughs",
  },
  {
    id: "rustc",
    name: "Rust",
    category: "runtime",
    description: "Rust programming language compiler",
    binary: "rustc",
    versionCommand: "rustc --version",
    versionParser: "regex",
    versionRegex: "rustc ([\\d.]+)",
    installUrl: "https://rustup.rs",
    installCommand: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh",
    updateCommands: { default: "rustup update" },
    detectInstallMethod: false,
    latestVersionSource: { type: "github-release", repo: "rust-lang/rust" },
    usedFor: "Inside — Desktop (Tauri) and Game (Bevy) projects",
  },
  {
    id: "cargo",
    name: "Cargo",
    category: "package-manager",
    description: "Rust package manager and build tool",
    binary: "cargo",
    versionCommand: "cargo --version",
    versionParser: "regex",
    versionRegex: "cargo ([\\d.]+)",
    installUrl: "https://rustup.rs",
    installCommand: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh",
    updateCommands: { default: "rustup update" },
    detectInstallMethod: false,
    latestVersionSource: { type: "none" },
    usedFor: "Inside — Desktop (Tauri) and Game (Bevy) projects",
  },
  {
    id: "tauri-cli",
    name: "Tauri CLI",
    category: "dev-tool",
    description: "Tauri app development CLI",
    binary: "cargo",
    versionCommand: "cargo tauri --version",
    versionParser: "regex",
    versionRegex: "tauri-cli ([\\d.]+)",
    installUrl: "https://v2.tauri.app",
    installCommand: "cargo install tauri-cli",
    updateCommands: { default: "cargo install tauri-cli" },
    detectInstallMethod: false,
    latestVersionSource: { type: "none" },
    usedFor: "Inside — Desktop apps with Tauri",
  },
  {
    id: "flutter",
    name: "Flutter",
    category: "dev-tool",
    description: "Cross-platform UI toolkit by Google",
    binary: "flutter",
    versionCommand: "flutter --version",
    versionParser: "regex",
    versionRegex: "Flutter ([\\d.]+)",
    installUrl: "https://flutter.dev/docs/get-started/install",
    installCommand: "brew install --cask flutter",
    updateCommands: { homebrew: "brew upgrade --cask flutter", default: "flutter upgrade" },
    latestVersionSource: { type: "github-release", repo: "flutter/flutter" },
    usedFor: "Inside — Mobile apps with Flutter",
  },
  {
    id: "dart",
    name: "Dart",
    category: "runtime",
    description: "Programming language for Flutter and server apps",
    binary: "dart",
    versionCommand: "dart --version",
    versionParser: "regex",
    versionRegex: "Dart SDK version: ([\\d.]+)",
    installUrl: "https://dart.dev/get-dart",
    installCommand: "brew install dart",
    updateCommands: { homebrew: "brew upgrade dart" },
    latestVersionSource: { type: "github-release", repo: "dart-lang/sdk" },
    usedFor: "Inside — Mobile apps with Flutter",
  },
  {
    id: "godot",
    name: "Godot",
    category: "dev-tool",
    description: "Open-source 2D/3D game engine",
    binary: "godot",
    versionCommand: "godot --version",
    versionParser: "first-line",
    installUrl: "https://godotengine.org/download",
    installCommand: "brew install --cask godot",
    updateCommands: { homebrew: "brew upgrade --cask godot" },
    latestVersionSource: { type: "github-release", repo: "godotengine/godot" },
    usedFor: "Inside — Game projects with Godot engine",
  },
];

export const DEFAULT_TOOL_IDS = DEFAULT_TOOLS.map((t) => t.id);

export function getToolById(id: string): ToolDefinition | undefined {
  return DEFAULT_TOOLS.find((t) => t.id === id);
}

/** Resolve the correct update command for a tool based on how it was installed. */
export function resolveUpdateCommand(
  tool: ToolDefinition,
  installMethod: InstallMethod | string | null,
): string | undefined {
  if (!tool.updateCommands) return undefined;
  if (installMethod && installMethod in tool.updateCommands) {
    return tool.updateCommands[installMethod as InstallMethod];
  }
  return tool.updateCommands.default;
}

export const TOOL_CATEGORY_LABELS: Record<ToolCategory, string> = {
  "ai-tool": "AI Tools",
  "package-manager": "Package Managers",
  runtime: "Runtimes",
  "dev-tool": "Dev Tools",
  vcs: "Version Control",
};
