import path from "node:path";

const EXTENSION_MAP: Record<string, string> = {
  ".ts": "typescript",
  ".tsx": "tsx",
  ".js": "javascript",
  ".jsx": "jsx",
  ".mjs": "javascript",
  ".cjs": "javascript",
  ".json": "json",
  ".jsonc": "jsonc",
  ".json5": "json5",
  ".md": "markdown",
  ".mdx": "mdx",
  ".css": "css",
  ".scss": "scss",
  ".less": "less",
  ".html": "html",
  ".htm": "html",
  ".xml": "xml",
  ".svg": "xml",
  ".yaml": "yaml",
  ".yml": "yaml",
  ".toml": "toml",
  ".py": "python",
  ".rb": "ruby",
  ".rs": "rust",
  ".go": "go",
  ".java": "java",
  ".kt": "kotlin",
  ".swift": "swift",
  ".c": "c",
  ".cpp": "cpp",
  ".h": "c",
  ".hpp": "cpp",
  ".cs": "csharp",
  ".php": "php",
  ".sh": "bash",
  ".bash": "bash",
  ".zsh": "bash",
  ".fish": "fish",
  ".ps1": "powershell",
  ".sql": "sql",
  ".graphql": "graphql",
  ".gql": "graphql",
  ".dockerfile": "dockerfile",
  ".proto": "protobuf",
  ".lua": "lua",
  ".r": "r",
  ".R": "r",
  ".dart": "dart",
  ".ex": "elixir",
  ".exs": "elixir",
  ".erl": "erlang",
  ".hs": "haskell",
  ".vue": "vue",
  ".svelte": "svelte",
  ".astro": "astro",
  ".prisma": "prisma",
  ".tf": "hcl",
  ".hcl": "hcl",
  ".ini": "ini",
  ".env": "dotenv",
  ".gitignore": "gitignore",
  ".dockerignore": "gitignore",
  ".editorconfig": "ini",
  ".lock": "text",
  ".log": "log",
  ".txt": "text",
  ".csv": "csv",
};

const FILENAME_MAP: Record<string, string> = {
  Dockerfile: "dockerfile",
  Makefile: "makefile",
  Rakefile: "ruby",
  Gemfile: "ruby",
  Justfile: "just",
  Vagrantfile: "ruby",
  Cakefile: "coffeescript",
  ".gitignore": "gitignore",
  ".dockerignore": "gitignore",
  ".npmrc": "ini",
  ".nvmrc": "text",
  ".prettierrc": "json",
  ".eslintrc": "json",
  ".babelrc": "json",
  "tsconfig.json": "jsonc",
  "jsconfig.json": "jsonc",
};

const BINARY_EXTENSIONS = new Set([
  ".png",
  ".jpg",
  ".jpeg",
  ".gif",
  ".bmp",
  ".ico",
  ".webp",
  ".avif",
  ".tiff",
  ".tif",
  ".svg",
  ".mp3",
  ".mp4",
  ".wav",
  ".ogg",
  ".webm",
  ".flac",
  ".aac",
  ".mov",
  ".avi",
  ".mkv",
  ".pdf",
  ".zip",
  ".gz",
  ".tar",
  ".bz2",
  ".xz",
  ".7z",
  ".rar",
  ".woff",
  ".woff2",
  ".ttf",
  ".otf",
  ".eot",
  ".exe",
  ".dll",
  ".so",
  ".dylib",
  ".a",
  ".o",
  ".obj",
  ".class",
  ".jar",
  ".war",
  ".ear",
  ".pyc",
  ".pyo",
  ".wasm",
  ".sqlite",
  ".db",
  ".duckdb",
]);

// SVG is not binary — it's XML text
BINARY_EXTENSIONS.delete(".svg");

export function detectLanguage(filePath: string): string {
  const basename = path.basename(filePath);

  if (FILENAME_MAP[basename]) return FILENAME_MAP[basename];

  const ext = path.extname(filePath).toLowerCase();
  return EXTENSION_MAP[ext] || "text";
}

export function isBinaryFile(filePath: string): boolean {
  const ext = path.extname(filePath).toLowerCase();
  return BINARY_EXTENSIONS.has(ext);
}
